In [62]:
import glob

files = glob.glob('./newsdata/2017/*/newsisall.json')

In [63]:
import json
def read_json_file(path_to_file):
    with open(path_to_file) as p:
        rows=[json.loads(line) for line in p]
    return rows

In [64]:
import pandas as pd

data=[]
for path in files:
    data.extend(read_json_file(path))

df = pd.DataFrame(data)

In [65]:
df=df.dropna(subset=['section'])
df=df.reset_index(drop=True)

In [66]:
df.drop(['naver_url','org_url'], axis = 1, inplace = True)

In [67]:
article=df['article'][10].replace('▶','\n▶').replace('\t', '').replace('\n', ' ')#.split('\n')
article

'   【서울=뉴시스】오종택 기자 = 용인 삼성생명이 정유년 새해 첫 경기를 연장 접전 끝에 잡고 3연승을 달렸다.   삼성생명은 1일 구리시체육관에서 벌어진 삼성생명 2016~2017 여자프로농구 구리 KDB생명과 경기에서 엘리사 토마스의 막판 활약에 힘입어 73-64로 승리했다.   이날 경기 전까지 2연승을 달린 두 팀은 2017년 정유년 새해 첫날 격돌했다. 승리한 팀은 새해 첫 승리과 함께 상승세를 이을 수 있는 좋은 기회였다.   경기 초반 삼성생명은 고아라와 배혜윤의 득점으로 13-5로 앞서 나갔다. 뒤지던 KDB생명은 1쿼터 막판 투입된 티아라 하킨스의 4득점으로 2점차로 마칠 수 있었다.   2쿼터 들어 양팀 득점이 침묵했다. KDB생명 이경은의 속공 득점으로 17-17로 동점을 이룬 뒤 2분여간 스코어에 변동이 없었다.    이후 삼성생명은 다시 분위기를 타는 듯 싶었지만 KDB생명 카리마 크리스마스의 페인트존 득점과 한채진의 자유투로 역전을 허용했다. 2쿼터 종료 직전 속공을 주고 받으며 28-28 동점으로 전반을 마쳤다.   3쿼터도 일진일퇴의 공방전이 펼쳐졌다. 역전의 재역전을 거듭한 끝에 53-53으로 동점 상황이 계속됐다.   4쿼터 삼성생명은 KDB생명에게 끌려갔다. 종료 3분25초를 남기고 이경은에게 3점슛을 얻어 맞고 52-58로 뒤졌다.    이후 김한별의 자유투와 고아라의 골밑 득점으로 다시 추격에 나섰다. 이번에는 크리스마스에게 레이업 득점에 이은 추가 자유투까지 내주며 패색이 짙었다.    그러나 삼성생명의 집중력이 돋보였다. 배혜윤이 상대 반칙으로 얻은 자유투를 모두 성공시켰고, 토마스는 크리스마스에게 집중된 공격을 잘 차단했다. 가로채기와 블록슛으로 크리스마스의 공격을 무력화했다.   이후 종료 10초를 남기고는 과감한 돌파로 득점에 성공, 승부를 연장으로 끌고 갔다.   토마스의 활약은 연장에서도 계속됐다. 박하나의 득점을 어시스트하고 고비마다 자유투를 얻어냈다. 1분8초를 남기고는 공격제한 시간과 동시에 던진 슛이 림을 갈랐다. 승리를 위한 9부 능선을 넘은 삼성생명은 막판 자유투를 적립하며 승리의 기쁨을 누렸다.   이날 승리로 3연승을 달린 삼성생명은 9승10패로 5할 승률을 목전에 뒀다. 반면 연승 행진을 중단한 KDB생명은 7승12패가 되며 신한은행과 함께 공동 4위가 됐다.   토마스가 4쿼터와 연장에서 맹활약을 펼치며 21점 15리바운드로 팀을 승리로 이끌었다. 고아라(14점)와 배혜윤(12점), 김한별(10점)도 두 자릿수 득점을 보탰다.   KDB생명은 크리스마스(17점)와 이경은(16점)이 분전했지만 연장에서 패하며 새해 첫 승의 기회를 다음으로 미뤄야 했다.   ohjt@newsis.com  뉴시스 뉴스, 네이버 뉴스 스탠드에서도 만나세요 뉴시스 SNS [페이스북] [트위터]    기사제공 뉴시스 '

In [68]:
import re

#article = re.sub(r'[a-zA-Z0-9]+@newsis.com(.*)', '', article)
article = re.sub(r'\【[a-zA-Z가-힣· ]+\=[a-zA-Z가-힣/ ]+\】[a-zA-Z가-힣· ]+ =|\【[a-zA-Z가-힣· ]+\=[a-zA-Z가-힣/ ]+\】|\<< [a-zA-Z가-힣· ]+\=[a-zA-Z가-힣· ]+ >>|\([a-zA-Z가-힣0-9·, ]+\=[a-zA-Z가-힣· ]+\)|\[[a-zA-Z가-힣·= ]+[자료사진 ]\]|\(연합뉴스 DB\)|\[[a-zA-Z가-힣 ]+제공\]|\[[a-zA-Z가-힣 ]+제공=연합뉴스\]', '', article)
article = re.sub(r'(20[0-9 ]+\.[0-9 ]+\.[0-9 ]+\.)(.*)', '', article)
article = re.sub(r'([a-z.0-9]+@newsis.com)(.*)', '', article)
article

'    용인 삼성생명이 정유년 새해 첫 경기를 연장 접전 끝에 잡고 3연승을 달렸다.   삼성생명은 1일 구리시체육관에서 벌어진 삼성생명 2016~2017 여자프로농구 구리 KDB생명과 경기에서 엘리사 토마스의 막판 활약에 힘입어 73-64로 승리했다.   이날 경기 전까지 2연승을 달린 두 팀은 2017년 정유년 새해 첫날 격돌했다. 승리한 팀은 새해 첫 승리과 함께 상승세를 이을 수 있는 좋은 기회였다.   경기 초반 삼성생명은 고아라와 배혜윤의 득점으로 13-5로 앞서 나갔다. 뒤지던 KDB생명은 1쿼터 막판 투입된 티아라 하킨스의 4득점으로 2점차로 마칠 수 있었다.   2쿼터 들어 양팀 득점이 침묵했다. KDB생명 이경은의 속공 득점으로 17-17로 동점을 이룬 뒤 2분여간 스코어에 변동이 없었다.    이후 삼성생명은 다시 분위기를 타는 듯 싶었지만 KDB생명 카리마 크리스마스의 페인트존 득점과 한채진의 자유투로 역전을 허용했다. 2쿼터 종료 직전 속공을 주고 받으며 28-28 동점으로 전반을 마쳤다.   3쿼터도 일진일퇴의 공방전이 펼쳐졌다. 역전의 재역전을 거듭한 끝에 53-53으로 동점 상황이 계속됐다.   4쿼터 삼성생명은 KDB생명에게 끌려갔다. 종료 3분25초를 남기고 이경은에게 3점슛을 얻어 맞고 52-58로 뒤졌다.    이후 김한별의 자유투와 고아라의 골밑 득점으로 다시 추격에 나섰다. 이번에는 크리스마스에게 레이업 득점에 이은 추가 자유투까지 내주며 패색이 짙었다.    그러나 삼성생명의 집중력이 돋보였다. 배혜윤이 상대 반칙으로 얻은 자유투를 모두 성공시켰고, 토마스는 크리스마스에게 집중된 공격을 잘 차단했다. 가로채기와 블록슛으로 크리스마스의 공격을 무력화했다.   이후 종료 10초를 남기고는 과감한 돌파로 득점에 성공, 승부를 연장으로 끌고 갔다.   토마스의 활약은 연장에서도 계속됐다. 박하나의 득점을 어시스트하고 고비마다 자유투를 얻어냈다. 1분8초를 남기고는 공격제한 시간과 동시에 던진 슛이 림을 갈랐다. 승리를 위한 9부 능선을 넘은 삼성생명은 막판 자유투를 적립하며 승리의 기쁨을 누렸다.   이날 승리로 3연승을 달린 삼성생명은 9승10패로 5할 승률을 목전에 뒀다. 반면 연승 행진을 중단한 KDB생명은 7승12패가 되며 신한은행과 함께 공동 4위가 됐다.   토마스가 4쿼터와 연장에서 맹활약을 펼치며 21점 15리바운드로 팀을 승리로 이끌었다. 고아라(14점)와 배혜윤(12점), 김한별(10점)도 두 자릿수 득점을 보탰다.   KDB생명은 크리스마스(17점)와 이경은(16점)이 분전했지만 연장에서 패하며 새해 첫 승의 기회를 다음으로 미뤄야 했다.   '

In [69]:
import re
def remove_extras(article):
    #return_article = ''
    article = re.sub(r'\/\/[a-zA-Z가-힣 \n]+|{}|_flash_removeCallback\(\)', '', article)
    article = article.replace('▶','\n▶').replace('\t', '').replace('\n', ' ')
    #remove by line
    article = re.sub(r'\【[a-zA-Z가-힣·\(\)\- ]+\=[a-zA-Z가-힣\/ ]+\】[a-zA-Z가-힣·\/ ]+ =|\【[a-zA-Z가-힣·\(\)\/\- ]+\=[a-zA-Z가-힣\/ ]+\】|\【[a-zA-Z가-힣·\(\)\/\- ]+\】|\<< [a-zA-Z가-힣· ]+\=[a-zA-Z가-힣· ]+ >>|\([a-zA-Z가-힣0-9·, ]+\=[a-zA-Z가-힣· ]+\)|\[[a-zA-Z가-힣·= ]+[자료사진 ]\]|\(연합뉴스 DB\)|\[[a-zA-Z가-힣 ]+제공\]|\[[a-zA-Z가-힣 ]+제공=연합뉴스\]', '', article)
    #remove copyrithgs
    #article = article.replace('<저작권자(c) 연합뉴스, 무단 전재-재배포 금지>', '')
    #remove email
    #article = re.sub(r'[a-zA-Z0-9_-]+@[a-z]+.[a-z]+.[a-z]+', '', article)
    #remove tail
    
    #for sentence in article.split('\n'):
    #    if not sentence.startswith('▶') : return_article += sentence

    #return_article = return_article.replace('\n', ' ')
    article = re.sub(r'(20[0-9 ]+\.[0-9 ]+\.[0-9 ]+\.)(.*)', '', article)
    article = re.sub(r'([a-z.0-9]+@newsis.com)(.*)', '', article)

    return article

In [70]:
df['article'][29]

'\n\n\n\n\n\n\n【AP/뉴시스】러시아는 6일 시리아 파견군의 철수를 시작한다고 발표했다. 사진은 4일 러시아 국방부 웹사이트에 올려진 항공모함 쿠츠네초프 제독 호가 동부 지중해에 머물러 시리아 공습을 돕고 있는 모습이다. 2017. 1. 6. \n\n[사진 영상 제보받습니다] 공감언론 뉴시스가 독자 여러분의 소중한 제보를 기다립니다. 뉴스 가치나 화제성이 있다고 판단되는 사진 또는 영상을 뉴시스 사진영상부(n-photo@newsis.com, 02-721-7470)로 보내주시면 적극 반영하겠습니다.\n\n\n\n\n'

In [71]:
print(remove_extras(df['article'][29]))

       러시아는 6일 시리아 파견군의 철수를 시작한다고 발표했다. 사진은 4일 러시아 국방부 웹사이트에 올려진 항공모함 쿠츠네초프 제독 호가 동부 지중해에 머물러 시리아 공습을 돕고 있는 모습이다.

In [72]:
df['article'].apply(lambda x: remove_extras(x))

0               더불어민주당 박경미 신임 대변인이 31일 오전 서울 여의도 국회 정론관에...
1               박근혜 대통령이 1일 청와대 상춘재 앞에서 출입기자단과 만나 환담을 나누...
2               국민의당 주승용 원내대표가 30일 오전 서울 여의도 국회 당 대표실에서 ...
3              ＊＊＊첨부용＊＊＊    1일 오후 5시26께 강원 태백시 상장동 1주공아파...
4                 유일호 경제부총리 겸 기획재정부 장관은 1일 새로 출범하는 트럼프 행...
5                 1일 오후 4시16분께 강원 홍천군 부촌면 배성리에 한 주택에서 불이...
6              운전기사 상습 폭언 및 폭행 등 갑질 논란에 휩싸인 이해욱 대림산업 부회장...
7               박근혜 대통령이 1일 청와대 상춘재에서 출입기자단과 신년 인사를 겸한 티...
8                미국에서 지난 주 실업수당 신청자가 크게 줄어 고용시장이 호전되고 있음...
9                 유일호 부총리가 새해를 맞아 1일 인천 연수구 인천신항 선광신컨테이너...
10            용인 삼성생명이 정유년 새해 첫 경기를 연장 접전 끝에 잡고 3연승을 달렸다...
11                더불어민주당 문재인 전 대표가 3일 오후 서울 성북구 장위2동 장위시...
12               방글라데시 다카 시장 건물이 3일 화재로 무너져 내려 있다. 2017....
13                3일 중국 중앙기상대는 수도 베이징과 톈진, 허베이성 수도권 지역, ...
14              새누리당 인명진 비상대책위원장이 3일 오후 서울 여의도 국회 의원회관에서...
15                ◇원주시,미세먼지 주의보 발령현황 실시간 전광판 송출   원주시는 지...
16              새누리당 정우택 원내대표가 6일 오후 서울 여의도 국회에서 열린 새누리당...
17               코스콤(구 한국증권전산)은 6일 개최한 임시주주총회에서 강신 신임 전무...
18               6일 오후 4시48분께 서울 성동구 한양여자대학교 정문 앞 도로에서 3...
19            6일 오후 경북 구미시 박정희체육관에서 열린 NH농협 2016-2017 V리...
20                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
21                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
22                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
23                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
24                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
25                6일 오후 서울 서초구 예술의전당 CJ 토월극장에서 열린 뮤지컬 '인...
26                헌재, 경찰에 소재탐지 촉탁 요청  경찰 "촉탁서 종로·강남서에 접수...
27                오후 7시30분~오후 10시30분 제한 허용   정유년(丁酉年) 새해...
28              조윤선(왼쪽) 문화체육관광부장관과 김영석 해양수산부장관이 6일 오전 서울...
29               러시아는 6일 시리아 파견군의 철수를 시작한다고 발표했다. 사진은 4일...
                                ...
633303        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633304        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633305        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633306           괴물신인 '워너원'을 '아재 가수' 윤종신이 눌렀다.   1일 방송된 ...
633307           고용노동부 김영주 장관과 직업능력개발 유공자, 우수 숙련기술인 및 유관...
633308        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633309           고용노동부 김영주 장관, 동탑산업훈장 수상을 수상한 박찬환 (주)다프엘...
633310         (고용노동부 원주지청 청사 전경)   고용노동부 원주지청은 1일부터 육아휴...
633311            제주에서 부부싸움을 벌이던 남편이 아내를 흉기로 수차례 찔러 숨지게 ...
633312        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633313        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633314        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633315        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633316        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633317        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633318        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633319        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633320        1일 오후 서울 송파구 잠실야구장에서 열린 2017 KBO 리그 LG 트윈스...
633321        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633322           정부는 방송통신위원회(위원장 이효성) 주관으로 제54회 방송의 날을 맞...
633323       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
633324        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633325        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633326        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633327        1일 오후 광주 북구 광주-기아챔피언스필드에서 열린 2017프로야구 KIA ...
633328       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
633329       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
633330       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
633331       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
633332       1일 경상북도 칠곡군 왜관에 위치한 파미힐스CC에서 열린 2017 DGB금융그...
Name: article, dtype: object

In [73]:
df['article']=df['article'].apply(lambda x: remove_extras(x))

In [74]:
counts=df.groupby('section').size()
sorted_counts=counts.sort_values(ascending=False)

In [75]:
sorted_counts

section
사회|사회일반         197730
정치|정치일반         120971
국제|국제일반          42921
경제|경제일반          34072
스포츠|야구           17593
산업|산업/기업         15760
전국|대구/경북         13743
스포츠|스포츠일반        12461
산업|유통/생활경제       11268
문화|문화일반          11035
전국|충북             9952
연예|연예일반           9887
전국|경남             9753
전국|대전/충남          9566
전국|광주/전남          8976
전국|전북             7740
전국|부산             7693
전국|경기남부           7067
스포츠|축구            6287
전국|강원             6277
스포츠|골프            5799
전국|울산             5175
전국|제주             4316
스포츠|농구            3512
전국|경기북부           2506
전국|서울             2443
정치|행정             2310
광장|부고             2201
사회|법원/검찰          2195
사회|환경/날씨          2093
                 ...
사회|생활정보             37
산업|통신               35
정치|탄핵가결             29
문화|음식/맛집            28
광장|동정               28
경제|국제경제             27
경제|공시               22
광장|크로스로드            19
산업|모바일              14
연예|스타               12
광장|인터뷰              10
광장|기자수첩              9
정치|최순실               8
정치|대선이슈              7
광장|기고                6
산업|과학                6
사회|수능                6
정치|개헌                5
연예|해외연예              5
산업|게임                4
광장|스토리칼럼             3
경제|MSI TOP 5         3
연예|드라마               3
산업|인터넷/SNS           2
문화|건강                2
경제|경제정책              2
광장|포럼세미나             1
경제|해외증시              1
산업|시승기/신차            1
경제|MSI 시황            1
dtype: int64

In [76]:
df.to_pickle('newsis_2017.pkl')

### Compare Memory Usage

```
df['article']=pd.Series([val for val in df['article'].str.replace(r'\r|\t|\n|\/\/[a-zA-Z가-힣 \n]+|{}|_flash_removeCallback\(\)|[a-zA-Z0-9]+@yonhapnews.co.kr|\[연합뉴스[a-zA-Z가-힣 ]+\]|\([a-zA-Z가-힣· ]+\=연합뉴스\)|\[[a-zA-Z가-힣 ]+\=연합뉴스\]|[a-zA-Z가-힣 ]+ 기자 \=|[a-zA-Z가-힣 ]+ 특파원 \=','')])
```

```
df['article']=df['article'].str.replace(r'\[연합뉴스[a-zA-Z가-힣 ]+\]|\([a-zA-Z가-힣· ]+\=연합뉴스\)|\[[a-zA-Z가-힣 ]+\=연합뉴스\]|[a-zA-Z가-힣 ]+ 기자 \=|[a-zA-Z가-힣 ]+ 특파원 \=','')
```

In [46]:
df.memory_usage(deep=True)

Index              80
article    1091458481
author      112432385
date         50537779
section      78009964
title       118746873
dtype: int64